//list of all questions to ask in No Esc
let questions = [
    {
        Qnum: 1,
        cost: 1,
        text: "What should we call you?",
        type: "Open",
        correctAnswer: "player",
        onCorrectResponse: "Well done Player",
        onIncorrectResponse: "Incorrect, we will only refer to you as Player",
        placeholder: "Player",
      },
    {
      Qnum: 2,
      cost: 1,
      text: "What is 1 + 1?",
      type: "Open",
      correctAnswer: "2",
      onCorrectResponse: "Correct, Player",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      onIncorrectResponse: "Incorrect",
      placeholder: "",
    },
    {
      Qnum: 3,
      cost: 1,
      text: "What is the missing number in the sequence 5 , 10, 15, __, 25 ?",
      type: "Open",
      correctAnswer: "20",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      placeholder: "",
    },
    
    {
        Qnum: 18,
        cost: 2,
        text: "Which of the following animals cannot fly?\nA) Sparrow\nB) Eagle\nC) Penguin\nD) Parrot",
        type: "MC",
        correctAnswer: "C",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "Penguins are flightless birds.",
        extremeWrongAnswer: "",
      },
      {
        Qnum: 19,
        cost: 2,
        text: "What is a baby goat called?\nA) Cub\nB) Kid\nC) Calf\nD) Foal",
        type: "MC",
        correctAnswer: "B",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "Incorrect",
        extremeWrongAnswer: "",
      },
      {
        Qnum: 24,
        cost: 5,
        text: "What is the square root of 144?",
        type: "Open",
        correctAnswer: "12",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "Incorrect",
        placeholder: "",
      },
      {
        Qnum: 27,
        cost: 10,
        text: "How many sides does a dodecagon have?\nA) 10\nB) 11\nC) 12\nD) 13",
        type: "MC",
        correctAnswer: "C",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "A dodecagon has 12 sides.",
        extremeWrongAnswer: "",
      },
      {
        Qnum: 32,
        cost: 2,
        text: "Which of the following is not a primary color?\nA) Red\nB) Blue\nC) Yellow\nD) Green",
        type: "MC",
        correctAnswer: "D",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "Green is made by mixing blue and yellow.",
        extremeWrongAnswer: "",
      },
      {
        Qnum: 36,
        cost: 3,
        text: "What is the largest organ in the human body?",
        type: "Open",
        correctAnswer: "skin",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "Incorrect",
        placeholder: "",
      },
      {
        Qnum: 41,
        cost: 3,
        text: "If you take two apples from a basket containing three apples, how many apples do you have?",
        type: "Open",
        correctAnswer: "two",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "Incorrect. You have two apples in your hand.",
        placeholder: "",
      },
      {
        Qnum: 45,
        cost: 2,
        text: "Which planet is known as the Red Planet?\nA) Venus\nB) Mars\nC) Jupiter\nD) Saturn",
        type: "MC",
        correctAnswer: "B",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "Mars is known as the Red Planet.",
        extremeWrongAnswer: "",
      },
      {
        Qnum: 46,
        cost: 2,
        text: "How many continents are there on Earth?",
        type: "Open",
        correctAnswer: "7",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "Incorrect",
        placeholder: "",
      },
      {
        Qnum: 48,
        cost: 3,
        text: "Which of the following is a prime number?\nA) 4\nB) 6\nC) 11\nD) 12",
        type: "MC",
        correctAnswer: "C",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "11 is a prime number.",
        extremeWrongAnswer: "",
      },
      {
        Qnum: 49,
        cost: 3,
        text: "What is the name of the closest star to Earth?",
        type: "Open",
        correctAnswer: "Sun",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "Incorrect",
        placeholder: "",
      },

      {
        Qnum: 52,
        cost: 5,
        text: "What is the capital city of France?",
        type: "Open",
        correctAnswer: "Paris",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "Incorrect",
        placeholder: "",
      },
      {
        Qnum: 54,
        cost: 10,
        text: "What is the main ingredient in traditional Japanese miso soup?",
        type: "Open",
        correctAnswer: "miso",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "Incorrect",
        placeholder: "",
      },
      {
        Qnum: 64,
        cost: 5,
        text: "What is the smallest prime number?",
        type: "Open",
        correctAnswer: "2",
        onCorrectResponse: "Correct, Player",
        onIncorrectResponse: "Incorrect",
        placeholder: "",
      },
      
        {
          Qnum: 97,
          cost: 3,
          text: "If a barber shaves all men in town who do not shave themselves, does the barber shave himself?",
          type: "Open",
          correctAnswer: "Paradox",
          onCorrectResponse: "Correct, Player",
          onIncorrectResponse: "Incorrect. It's known as the Barber Paradox.",
          placeholder: "",
        },
        {
          Qnum: 98,
          cost: 3,
          text: "If a liar says, 'I am lying,' is the statement true or false?",
          type: "Open",
          correctAnswer: "Paradox",
          onCorrectResponse: "Correct, Player",
          onIncorrectResponse: "Incorrect. This is the classic Liar's Paradox.",
          placeholder: "",
        },
        {
          Qnum: 99,
          cost: 5,
          text: "Can an omnipotent being create a rock so heavy that it cannot lift it?",
          type: "Open",
          correctAnswer: "Paradox",
          onCorrectResponse: "Correct, Player",
          onIncorrectResponse: "Incorrect. This is the Omnipotence Paradox.",
          placeholder: "",
        },
        {
          Qnum: 100,
          cost: 5,
          text: "If the present determines the future, but the past determines the present, who decides the past?",
          type: "Open",
          correctAnswer: "Paradox",
          onCorrectResponse: "Correct, Player",
          onIncorrectResponse: "Incorrect. This relates to causal loops.",
          placeholder: "",
        },
        {
          Qnum: 101,
          cost: 8,
          text: "A person travels back in time and kills their own grandfather before their parent is born. How did they exist to travel back in time?",
          type: "Open",
          correctAnswer: "Paradox",
          onCorrectResponse: "Correct, Player",
          onIncorrectResponse: "Incorrect. This is the Grandfather Paradox.",
          placeholder: "",
        },
        {
          Qnum: 102,
          cost: 8,
          text: "If you say, 'This statement is false,' is the statement true or false?",
          type: "Open",
          correctAnswer: "Paradox",
          onCorrectResponse: "Correct, Player",
          onIncorrectResponse: "Incorrect. This is a self-referential paradox.",
          placeholder: "",
        },
        {
          Qnum: 103,
          cost: 10,
          text: "If a ship has all its parts replaced one by one, is it still the same ship?",
          type: "Open",
          correctAnswer: "Paradox",
          onCorrectResponse: "Correct, Player",
          onIncorrectResponse: "Incorrect. This is the Ship of Theseus paradox.",
          placeholder: "",
        },
        {
          Qnum: 104,
          cost: 10,
          text: "If a hotel with infinitely many rooms is fully occupied, can it still accommodate new guests?",
          type: "Open",
          correctAnswer: "Yes",
          onCorrectResponse: "Correct, Player",
          onIncorrectResponse: "Incorrect. This is a concept from Hilbert’s Hotel.",
          placeholder: "",
        },
        {
          Qnum: 105,
          cost: 15,
          text: "If you go back in time and prevent your own birth, who went back in time?",
          type: "Open",
          correctAnswer: "Paradox",
          onCorrectResponse: "Correct, Player",
          onIncorrectResponse: "Incorrect. This is another form of the Grandfather Paradox.",
          placeholder: "",
        },
        {
          Qnum: 106,
          cost: 15,
          text: "If you predict something will not happen and your prediction causes it to happen, were you right or wrong?",
          type: "Open",
          correctAnswer: "Paradox",
          onCorrectResponse: "Correct, Player",
          onIncorrectResponse: "Incorrect. This is a paradox of self-fulfilling prophecy.",
          placeholder: "",
        },
        {
          Qnum: 107,
          cost: 20,
          text: "If a cat is in a box and you cannot observe it, is the cat alive, dead, or both?",
          type: "Open",
          correctAnswer: "Both",
          onCorrectResponse: "Correct, Player",
          onIncorrectResponse: "Incorrect. This is Schrödinger's Cat thought experiment.",
          placeholder: "",
        },
        {
          Qnum: 108,
          cost: 20,
          text: "If the unstoppable force meets the immovable object, what happens?",
          type: "Open",
          correctAnswer: "Paradox",
          onCorrectResponse: "Correct, Player",
          onIncorrectResponse: "Incorrect. This is an example of an irresolvable paradox.",
          placeholder: "",
        },
        {
            Qnum: 102,
            cost: 8,
            text: "If you say, 'This statement is false,' is the statement true or false?",
            type: "Open",
            correctAnswer: "Paradox",
            onCorrectResponse: "Correct, Player",
            onIncorrectResponse: "Incorrect. This is a self-referential paradox.",
            placeholder: "",
          },
          {
            Qnum: 103,
            cost: 10,
            text: "If a ship has all its parts replaced one by one, is it still the same ship?",
            type: "Open",
            correctAnswer: "Paradox",
            onCorrectResponse: "Correct, Player",
            onIncorrectResponse: "Incorrect. This is the Ship of Theseus paradox.",
            placeholder: "",
          },
          {
            Qnum: 104,
            cost: 10,
            text: "If a hotel with infinitely many rooms is fully occupied, can it still accommodate new guests?",
            type: "Open",
            correctAnswer: "Yes",
            onCorrectResponse: "Correct, Player",
            onIncorrectResponse: "Incorrect. This is a concept from Hilbert’s Hotel.",
            placeholder: "",
          },
          {
            Qnum: 124,
            cost: 12,
            text: "What occurs once in every minute, twice in every moment, but never in a thousand years?",
            type: "Open",
            correctAnswer: "The letter M",
            onCorrectResponse: "Correct, Player",
            onIncorrectResponse: "Incorrect. The answer is the letter M.",
            placeholder: "",
          },
          {
            Qnum: 138,
            cost: 35,
            text: "I have keys but no locks. I have space but no room. You can enter, but you can’t go outside. What am I?",
            type: "Open",
            correctAnswer: "A keyboard",
            onCorrectResponse: "Correct, Player",
            onIncorrectResponse: "Incorrect. The answer is a keyboard.",
            placeholder: "",
          },
          // can change to mc
          {
            Qnum: 143,
            cost: 50,
            text: "If you are running a race and you pass the person in second place, what place are you in?",
            type: "Open",
            correctAnswer: "Second place",
            onCorrectResponse: "Correct, Player",
            onIncorrectResponse: "Incorrect. The answer is second place.",
            placeholder: "",
          },
          {
            Qnum: 145,
            cost: 15,
            text: "What has to be broken before you can use it?",
            type: "Open",
            correctAnswer: "An egg",
            onCorrectResponse: "Correct, Player",
            onIncorrectResponse: "Incorrect. The answer is an egg.",
            placeholder: "",
          },
          {
            Qnum: 146,
            cost: 20,
            text: "What can you catch but not throw?",
            type: "Open",
            correctAnswer: "A cold",
            onCorrectResponse: "Correct, Player",
            onIncorrectResponse: "Incorrect. The answer is a cold.",
            placeholder: "",
          },
          {
            Qnum: 147,
            cost: 25,
            text: "What has hands but can’t clap?",
            type: "Open",
            correctAnswer: "A clock",
            onCorrectResponse: "Correct, Player",
            onIncorrectResponse: "Incorrect. The answer is a clock.",
            placeholder: "",
          },
          {
            Qnum: 148,
            cost: 30,
            text: "What has legs but doesn’t walk?",
            type: "Open",
            correctAnswer: "A table",
            onCorrectResponse: "Correct, Player",
            onIncorrectResponse: "Incorrect. The answer is a table.",
            placeholder: "",
          },
          {
            Qnum: 149,
            cost: 35,
            text: "What has teeth but can’t bite?",
            type: "Open",
            correctAnswer: "A comb",
            onCorrectResponse: "Correct, Player",
            onIncorrectResponse: "Incorrect. The answer is a comb.",
            placeholder: "",
          },
          {
            Qnum: 153,
            cost: 55,
            text: "What has a head, a tail, but no body?",
            type: "Open",
            correctAnswer: "A coin",
            onCorrectResponse: "Correct, Player",
            onIncorrectResponse: "Incorrect. The answer is a coin.",
            placeholder: "",
          },
          {
            Qnum: 182,
            cost: 300,
            text: "What can be heard but never seen?",
            type: "Open",
            correctAnswer: "A scream",
            onCorrectResponse: "Correct, Player",
            onIncorrectResponse: "Incorrect. The answer is a scream.",
            placeholder: "",
          },
      
    {
      Qnum: 4,
      cost: 2,
      text: `Which of the following words doesn't belong?\nA) Doctor\nB) Writer\nC) Teacher\nD) Murderer`,
      type: "MC",
      correctAnswer: "A",
      choices:["Doctor", "Writer","Teacher","Murderer"],
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse:
        "Only Doctor ends with 'or' and whose stem is not a verb",
      extremeWrongAnswer: "",
    },
    {
      Qnum: 5,
      cost: 2,
      text: "What is a group of crows called?\nA) A Killing\nB) A Murder\nC) An Assassination\nD) Crows",
      type: "MC",
      correctAnswer: "B",
      choices:["A Killing","A Murder","An Assassination","Crows"],
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Are you even trying?",
      extremeWrongAnswer: "",
    },
    {
      Qnum: 6,
      cost: 2,
      text: "Fill in the blank, the _____ Sea is most known for its high salt concentration which prevents many aquatic life and plants from living in it.",
      type: "Open",
      correctAnswer: "dead",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      placeholder: "",
    },
    {
      Qnum: 7,
      cost: 3,
      text: "Which of the following is the fear of machines?\nA) Motorphobia\nB) Automatonophobia\nC) Metathesiophobia\nD) Mechanophobia",
      type: "MC",
      correctAnswer: "D",
      choices:["Motorphobia","Automatonophobia","Metathesiophobia","Mechanophobia"],
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      extremeWrongAnswer: "",
    },
    {
      Qnum: 8,
      cost: 3,
      text: "What four-letter word can be written forward, backward or upside down, and can still be read from left to right?",
      type: "Open",
      correctAnswer: "noon",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      placeholder: "",
    },
    {
      Qnum: 9,
      cost: 3,
      text: "What is at the end of 'the rainbow'?\nA) Pot of gold\nB) w\nC) leprechaun\nD) the ground",
      type: "MC",
      correctAnswer: "B",
      choices:["Pot of Gold", "w","lepreschaun", "the ground"],
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "w ends the phrase 'the rainbow'",
      extremeWrongAnswer: "The imaginary creature?",
    },
    {
      Qnum: 10,
      cost: 3,
      text: "What word is always spelled wrong?",
      type: "Open",
      correctAnswer: "wrong",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      placeholder: "",
    },
    {
      Qnum: 11,
      cost: 5,
      text: "Do you think you will win?",
      type: "Confirm",
      correctAnswer: true,
      onCorrectResponse: "Interesting...",
      onIncorrectResponse: "Good.",
      placeholder: "",
    },
    {
      Qnum: 12,
      cost: 5,
      text: "What is zero to the power of 0?\nA) 1\nB) 0\nC) infinity\nD) -infinity",
      type: "MC",
      correctAnswer: "A",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      extremeWrongAnswer: "",
    },
    {
      Qnum: 13,
      cost: 5,
      text: "What is Infinity divided by 0?\nA) 1\nB) 0\nC) infinity\nD) -infinity",
      type: "MC",
      correctAnswer: "C",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      extremeWrongAnswer: "",
    },
    {
      Qnum: 14,
      cost: 5,
      text: "What is 0 divided by Infinity?\nA) 1\nB) 0\nC) infinity\nD) -infinity",
      type: "MC",
      correctAnswer: "B",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      extremeWrongAnswer: "",
    },
    {
      Qnum: 15,
      cost: 10,
      text: "How many points will the next Questions cost?\nA) All\nB) Everything\nC) 0\nD) infinity",
      type: "MC",
      correctAnswer: "D",
      onCorrectResponse: "That's a good sport",
      onIncorrectResponse: "That's not a number",
      extremeWrongAnswer: "Have you given up?",
    },
    {
      Qnum: 16,
      cost: Infinity,
      text: "Is the following statement true or false? 'This sentence is false.'",
      type: "Open",
      correctAnswer: "neither",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "If the statement is true, then it is false or vice versa.",
      placeholder: "",
    },
  ];
  

export default questions;
