//list of all questions to ask in No Esc
let questions = [
    {
        Qnum: 1,
        cost: 1,
        text: "What should we call you?",
        type: "Open",
        correctAnswer: "player",
        onCorrectResponse: "Well done Player",
        onIncorrectResponse: "Incorrect, we will only refer to you as Player",
        placeholder: "Player",
      },
    {
      Qnum: 2,
      cost: 1,
      text: "What is 1 + 1?",
      type: "Open",
      correctAnswer: "2",
      onCorrectResponse: "Correct, Player",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      onIncorrectResponse: "Incorrect",
      placeholder: "",
    },
    {
      Qnum: 3,
      cost: 1,
      text: "What is the missing number in the sequence 5 , 10, 15, __, 25 ?",
      type: "Open",
      correctAnswer: "20",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      placeholder: "",
    },
    {
      Qnum: 4,
      cost: 2,
      text: `Which of the following words doesn't belong?\nA) Doctor\nB) Writer\nC) Teacher\nD) Murderer`,
      type: "MC",
      correctAnswer: "A",
      choices:["Doctor", "Writer","Teacher","Murderer"],
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse:
        "Only Doctor ends with 'or' and whose stem is not a verb",
      extremeWrongAnswer: "",
    },
    {
      Qnum: 5,
      cost: 2,
      text: "What is a group of crows called?\nA) A Killing\nB) A Murder\nC) An Assassination\nD) Crows",
      type: "MC",
      correctAnswer: "B",
      choices:["A Killing","A Murder","An Assassination","Crows"],
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Are you even trying?",
      extremeWrongAnswer: "",
    },
    {
      Qnum: 6,
      cost: 2,
      text: "Fill in the blank, the _____ Sea is most known for its high salt concentration which prevents many aquatic life and plants from living in it.",
      type: "Open",
      correctAnswer: "dead",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      placeholder: "",
    },
    {
      Qnum: 7,
      cost: 3,
      text: "Which of the following is the fear of machines?\nA) Motorphobia\nB) Automatonophobia\nC) Metathesiophobia\nD) Mechanophobia",
      type: "MC",
      correctAnswer: "D",
      choices:["Motorphobia","Automatonophobia","Metathesiophobia","Mechanophobia"],
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      extremeWrongAnswer: "",
    },
    {
      Qnum: 8,
      cost: 3,
      text: "What four-letter word can be written forward, backward or upside down, and can still be read from left to right?",
      type: "Open",
      correctAnswer: "noon",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      placeholder: "",
    },
    {
      Qnum: 9,
      cost: 3,
      text: "What is at the end of 'the rainbow'?\nA) Pot of gold\nB) w\nC) leprechaun\nD) the ground",
      type: "MC",
      correctAnswer: "B",
      choices:["Pot of Gold", "w","lepreschaun", "the ground"],
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "w ends the phrase 'the rainbow'",
      extremeWrongAnswer: "The imaginary creature?",
    },
    {
      Qnum: 10,
      cost: 3,
      text: "What word is always spelled wrong?",
      type: "Open",
      correctAnswer: "wrong",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      placeholder: "",
    },
    {
      Qnum: 11,
      cost: 5,
      text: "Do you think you will win?",
      type: "Confirm",
      correctAnswer: true,
      onCorrectResponse: "Interesting...",
      onIncorrectResponse: "Good.",
      placeholder: "",
    },
    {
      Qnum: 12,
      cost: 5,
      text: "What is zero to the power of 0?\nA) 1\nB) 0\nC) infinity\nD) -infinity",
      type: "MC",
      correctAnswer: "A",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      extremeWrongAnswer: "",
    },
    {
      Qnum: 13,
      cost: 5,
      text: "What is Infinity divided by 0?\nA) 1\nB) 0\nC) infinity\nD) -infinity",
      type: "MC",
      correctAnswer: "C",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      extremeWrongAnswer: "",
    },
    {
      Qnum: 14,
      cost: 5,
      text: "What is 0 divided by Infinity?\nA) 1\nB) 0\nC) infinity\nD) -infinity",
      type: "MC",
      correctAnswer: "B",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "Incorrect",
      extremeWrongAnswer: "",
    },
    {
      Qnum: 15,
      cost: 10,
      text: "How many points will the next Questions cost?\nA) All\nB) Everything\nC) 0\nD) infinity",
      type: "MC",
      correctAnswer: "D",
      onCorrectResponse: "That's a good sport",
      onIncorrectResponse: "That's not a number",
      extremeWrongAnswer: "Have you given up?",
    },
    {
      Qnum: 16,
      cost: Infinity,
      text: "Is the following statement true or false? 'This sentence is false.'",
      type: "Open",
      correctAnswer: "neither",
      onCorrectResponse: "Correct, Player",
      onIncorrectResponse: "If the statement is true, then it is false or vice versa.",
      placeholder: "",
    },
  ];
  

export default questions;
